title: words from the night
email: serenadantingchen@gmail.com
description: > 
  An experiment in a moment of boredom
baseurl: "/night"
url: https://heisenburger.github.io/night/
#url: "lab.serena.nz/wordsfromthenight"
twitter_username: sereeena
github_username:  heisenburger

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  sass_dir: _sass
  style: compressed

theme: jekyll-theme-cayman