title: words from the night
email: davidblue@extratone.com
description: > 
  An experiment in a moment of boredom (DUPLICATE OF @heisenburger/night)
baseurl: "/crt"
url: https://extratone.github.io/crt/
#url: "lab.serena.nz/wordsfromthenight"
twitter_username: NeoYokel
github_username:  extratone

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  sass_dir: _sass
  style: compressed
